### PR TITLE
New file button

### PR DESCRIPTION
**Pull request by Bashamega**
Hello:)
I have added a new feature that let's you create empty .py files

### CODE REVIEW

**Comment by 1lolplayer1** [comment]
I'll review and merge. thanks for helping!

**Comment by Bashamega** [comment]
> I'll review and merge. thanks for helping!

Your welcome

**Comment by SquidsHub** [comment]
Thanks

**Comment by 1lolplayer1** [comment]
So heres the problem this code is outdated version. I updated things after that so I just inserted new code from that file to main. 
**I will close this commit, new file code is inserted in main file**

**Pull request closed without merging**
